// TapeKidsOrbitSlider.vue
<template>
  <section
    class="hero-orbit-section"
    ref="sectionRef"
    @pointermove="onSectionPointerMove"
    @pointerleave="onSectionPointerLeave"
  >
    <div class="hero-atmosphere"></div>

    <!-- Earth & Slides Container: max-width 90vw, centered in viewport -->
    <div class="orbit-component-container">
      <div
        class="orbit-viewport"
        :class="{ 'is-dragging': isDragging }"
        ref="viewportRef"
        @pointerdown="onPointerDown"
        @mouseenter="isHovered = true"
        @mouseleave="isHovered = false"
      >
        <!-- 3D Orbit Stage where Earth & Cards reside as direct siblings -->
        <div class="orbit-stage">
          <!-- Guide ring -->
          <div class="orbit-ring-guide" :style="guideRingStyle"></div>

          <!-- Earth in the Middle (Hardware WebGL with Transparent Oceans) -->
          <div class="earth-container">
            <canvas
              ref="earthCanvasRef"
              class="earth-canvas"
            ></canvas>
            <div class="earth-atmosphere-glow"></div>
          </div>

          <!-- Cards as direct siblings of the earth -->
          <div
            v-for="(card, index) in items"
            :key="card.id || index"
            class="orbit-card"
            :class="{ 'is-active': activeIndex === index }"
            :style="cardStyles[index]"
            @click="onCardClick(index)"
          >
            <div class="card-inner">
              <img class="card-image" :src="card.image" :alt="card.title" loading="lazy" />
              <div class="card-scrim"></div>
              <div v-if="card.category" class="card-badge">{{ card.category }}</div>
              <h3 class="card-title">{{ card.title }}</h3>
            </div>
          </div>
        </div>
      </div>

      <!-- Chevrons -->
      <button class="nav-arrow prev" @click="stepPrev" aria-label="Previous card">
        <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
          <polyline points="15 18 9 12 15 6"></polyline>
        </svg>
      </button>
      <button class="nav-arrow next" @click="stepNext" aria-label="Next card">
        <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
          <polyline points="9 18 15 12 9 6"></polyline>
        </svg>
      </button>
    </div>

    <!-- Bottom Contrasting Half-Circle Pedestal (comes up 4-6rem from bottom edge) -->
    <div class="bottom-half-circle-pedestal">
      <!-- Bullets / Dots -->
      <div class="orbit-dots">
        <button
          v-for="(card, index) in items"
          :key="'dot-' + index"
          class="orbit-dot"
          :class="{ 'is-active': activeIndex === index }"
          :aria-label="`Go to ${card.title}`"
          @click="rotateToIndex(index)"
        ></button>
      </div>

      <!-- All Updates Button -->
      <router-link v-if="allUpdatesLink" :to="allUpdatesLink" class="all-updates-btn">
        All Updates
        <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
          <polyline points="9 18 15 12 9 6"></polyline>
        </svg>
      </router-link>
    </div>
  </section>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onBeforeUnmount } from 'vue';

export interface OrbitCardItem {
  id: string | number;
  title: string;
  category?: string;
  image: string;
  url?: string;
}

const props = withDefaults(
  defineProps<{
    items?: OrbitCardItem[];
    globeMode?: 'webgl' | 'video';
    globeTextureSrc?: string;
    globeVideoSrc?: string;
    globePosterSrc?: string;
    allUpdatesLink?: string;
    autoRotateSpeed?: number;
  }>(),
  {
    globeMode: 'webgl',
    globeTextureSrc: '/earth-texture.png',
    items: () => [
      {
        id: "its-in-you",
        title: "It's In You",
        category: "Creations",
        image: "https://content.branham.org/assets/1/1207762fc30598f35e7262400dfc2b8528b032c5d89cccd6fd33581fa77e6623d8a701e8a2c0f9b9d6fde6e9b00c6d72d5ae2b9a8147676a928b055b5529ee36.jpg"
      },
      {
        id: "god-rich-mercy",
        title: "The God Who Is Rich In Mercy",
        category: "Updates",
        image: "https://content.branham.org/assets/1/ab15cb9a63ce0bf60b33e90bc7d110578b1dcadcf36db9ba72019aa644056842c9ae8c67f3861c462b1f51158636ced1362d45c9a0d24f44274fd5d899a4fe66.jpg"
      },
      {
        id: "coloring-book-stats",
        title: "Coloring Book Stats",
        category: "Creations",
        image: "https://content.branham.org/assets/1/a8cd614bf399629ea9aecf455a8a243064d1529900aba8957946759940433587d12a30ee73ae5894f207cd561b924cc7cf997facd0eda45aa7e61915692485db.jpg"
      },
      {
        id: "wesley-birthplace",
        title: "John Wesley's Birthplace",
        category: "History",
        image: "https://content.branham.org/assets/1/77a4cd54ab94035f9912126356f7466c0d8c8df36ca18e28cdb0f26fddb75a9aa2b37b226aa009b4339d202ef6d2ab437da82dca9558441d130ef7067c02ac89.png"
      },
      {
        id: "save-tapekids-app",
        title: "Save TapeKids.org to your smartphone home screen",
        category: "Tips",
        image: "https://content.branham.org/assets/1/e0a22d013c3842d1d6ef52771f53bba97f6c290ce55036199e76993615d007109d22d56d801e1b44ebe5605be1e0c2e9aed9c01638c0671e670e5f42bdf0f3b7.jpg"
      },
      {
        id: "laodicean-age",
        title: "The Laodicean Church Age",
        category: "Church Ages",
        image: "https://content.branham.org/assets/1/9eaee6098b2c9e9eaceeb142b61a576389ba617f330e9ebeabc2cf68ffc69ba9b558edd23a895c5983c7c6a0f8a4f883fb46ec5f6e34177186dded38e92b0145.jpg"
      }
    ],
    allUpdatesLink: "/updates",
    autoRotateSpeed: 0.0016
  }
);

const emit = defineEmits<{
  (e: 'cardClick', card: OrbitCardItem, index: number): void;
  (e: 'activeChange', index: number): void;
}>();

const sectionRef = ref<HTMLElement | null>(null);
const viewportRef = ref<HTMLElement | null>(null);
const earthCanvasRef = ref<HTMLCanvasElement | null>(null);

let threeScene: any = null;
let threeCamera: any = null;
let threeRenderer: any = null;
let threeGlobe: any = null;
let lastAngle = 0;

const N = computed(() => props.items.length);
const stepAngle = computed(() => (2 * Math.PI) / N.value);

const currentAngle = ref(0);
const targetAngle = ref(0);
const velocity = ref(0);
const isDragging = ref(false);
const isHovered = ref(false);
const activeIndex = ref(0);

// Subtle Mouseover Parallax State
const targetMouseX = ref(0);
const targetMouseY = ref(0);
let smoothMouseX = 0;
let smoothMouseY = 0;

let startX = 0;
let lastX = 0;
let lastTime = 0;
let hasMoved = false;
let animFrameId: number | null = null;
let lastTickTime = performance.now();

const cardStyles = ref<Record<string, string>[]>([]);
const guideRingStyle = ref<Record<string, string>>({});

function getOrbitParams() {
  const w = typeof window !== 'undefined' ? window.innerWidth : 1200;
  let earthSize: number, cardW: number, tiltDeg: number, cardScaleMin: number;

  if (w <= 640) {
    earthSize = Math.min(w * 0.80, 390);
    cardW = Math.min(w * 0.46, 205);
    tiltDeg = 7;
    cardScaleMin = 0.62;
  } else if (w <= 1024) {
    earthSize = Math.min(w * 0.66, 530);
    cardW = Math.min(w * 0.22, 220);
    tiltDeg = 8;
    cardScaleMin = 0.68;
    const rGlobe = earthSize / 2;
    const minClearanceRx = (rGlobe + (cardW / 2) + 10) / 0.866;
    const maxRx = (w / 2) - (cardW / 2) - 18;
    const rx = Math.min(maxRx, Math.max(minClearanceRx, w * 0.40));
    const rz = Math.round(rx * 0.52);
    return { rx, rz, tiltDeg, cardScaleMin, earthSize };
  } else {
    // 72vw max on large screens
    earthSize = Math.min(w * 0.72, 840);
    cardW = Math.min(w * 0.14, 230);
    tiltDeg = 9;
    cardScaleMin = 0.70;
    const rGlobe = earthSize / 2;
    const minClearanceRx = (rGlobe + (cardW / 2) + 16) / 0.866;
    const maxRx = (w / 2) - (cardW / 2) - 32;
    const rx = Math.min(maxRx, Math.max(minClearanceRx, w * 0.40));
    const rz = Math.round(rx * 0.54);
    return { rx, rz, tiltDeg, cardScaleMin, earthSize };
  }
}

function updatePositions() {
  const { rx, rz, tiltDeg, cardScaleMin } = getOrbitParams();
  const tiltRad = (tiltDeg * Math.PI) / 180;
  const count = N.value;
  const step = stepAngle.value;

  guideRingStyle.value = {
    width: `${(rx * 2 + 80).toFixed(0)}px`,
    height: `${(rz * 2 + 50).toFixed(0)}px`,
    marginLeft: `-${(rx + 40).toFixed(0)}px`,
    marginTop: `-${(rz + 25).toFixed(0)}px`,
    transform: 'rotateX(74deg)'
  };

  let closestDist = Infinity;
  let newActive = activeIndex.value;
  const newStyles: Record<string, string>[] = [];

  for (let i = 0; i < count; i++) {
    const theta = currentAngle.value + i * step;
    const cosT = Math.cos(theta);
    const sinT = Math.sin(theta);

    const x = sinT * rx;
    const z = cosT * rz;
    const y = -cosT * Math.sin(tiltRad) * 65;

    const normZ = (z + rz) / (2 * rz);

    // Active Card ~1.3x Larger Hero Scaling
    const baseScale = cardScaleMin + normZ * (1.0 - cardScaleMin);
    const focalBoost = Math.pow(normZ, 2.8) * 0.36;
    const scale = baseScale + focalBoost;

    const rotateY = -sinT * 22;
    const rotateZ = -sinT * 2.5;

    // Subtle mouseover animation pull (active card pulls most noticeably, disabled during drag):
    const pullFactor = 0.35 + 0.65 * Math.pow(normZ, 2.0);
    const pullX = isDragging.value ? 0 : smoothMouseX * 16 * pullFactor;
    const pullY = isDragging.value ? 0 : smoothMouseY * 5 * pullFactor;
    const pullRotY = isDragging.value ? 0 : smoothMouseX * 2.5 * pullFactor;
    const pullRotX = isDragging.value ? 0 : -smoothMouseY * 1.5 * pullFactor;

    // Inactive cards: fully opaque with realistic contrast & depth attenuation
    const contrast = 0.72 + normZ * 0.28;
    const brightness = 0.88 + normZ * 0.12;

    let zIndex: number;
    let opacity: string;
    let pointerEvents: string;
    let visibility: string;
    let filter = 'none';

    if (normZ >= 0.55) {
      // Front hemisphere: 100% FULLY OPAQUE, crisp, interactive
      zIndex = 70 + Math.round(normZ * 30);
      opacity = '1';
      pointerEvents = 'auto';
      visibility = 'visible';
      if (normZ <= 0.88) {
        filter = `contrast(${contrast.toFixed(2)}) brightness(${brightness.toFixed(2)})`;
      }
    } else if (normZ >= 0.45) {
      // Horizon edge transition: smoothly fades in/out as cards round behind the globe
      const fade = (normZ - 0.45) / 0.1;
      zIndex = 55 + Math.round(normZ * 10);
      opacity = fade.toFixed(3);
      pointerEvents = 'none';
      visibility = 'visible';
      filter = `contrast(${contrast.toFixed(2)}) brightness(${brightness.toFixed(2)})`;
    } else {
      // Far side of the globe: strictly hidden to eliminate any overlapping or ghosting
      zIndex = 1;
      opacity = '0';
      pointerEvents = 'none';
      visibility = 'hidden';
    }

    newStyles.push({
      transform: `perspective(1200px) translate3d(${(x + pullX).toFixed(1)}px, ${(y + pullY).toFixed(1)}px, 0) rotateX(${pullRotX.toFixed(1)}deg) rotateY(${(rotateY + pullRotY).toFixed(1)}deg) rotateZ(${rotateZ.toFixed(1)}deg) scale(${scale.toFixed(3)})`,
      zIndex: String(zIndex),
      opacity,
      pointerEvents,
      visibility,
      filter
    });

    const normAngle = ((theta % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);
    const distToCenter = Math.min(normAngle, 2 * Math.PI - normAngle);
    if (distToCenter < closestDist) {
      closestDist = distToCenter;
      newActive = i;
    }
  }

  cardStyles.value = newStyles;

  if (newActive !== activeIndex.value) {
    activeIndex.value = newActive;
    emit('activeChange', newActive);
  }
}

function tick() {
  smoothMouseX += (targetMouseX.value - smoothMouseX) * 0.08;
  smoothMouseY += (targetMouseY.value - smoothMouseY) * 0.08;

  if (!isDragging.value) {
    if (Math.abs(velocity.value) > 0.0002) {
      currentAngle.value += velocity.value;
      velocity.value *= 0.92;
    } else {
      velocity.value = 0;
      const diff = targetAngle.value - currentAngle.value;
      if (Math.abs(diff) > 0.0002) {
        currentAngle.value += diff * 0.12;
      } else {
      }
    }
  }

  const sliderDelta = currentAngle.value - lastAngle;
  lastAngle = currentAngle.value;

  if (threeRenderer && threeScene && threeCamera && threeGlobe) {
    threeGlobe.rotation.y += 0.0028 + sliderDelta * 0.85;
    threeRenderer.render(threeScene, threeCamera);
  }

  updatePositions();
  animFrameId = requestAnimationFrame(tick);
}

function onPointerDown(e: PointerEvent) {
  if (e.button !== 0) return;
  isDragging.value = true;
  hasMoved = false;
  startX = e.clientX;
  lastX = startX;
  lastTime = performance.now();
  velocity.value = 0;

  window.addEventListener('pointermove', onPointerMove);
  window.addEventListener('pointerup', onPointerUp);
  window.addEventListener('pointercancel', onPointerUp);
}

function onPointerMove(e: PointerEvent) {
  if (!isDragging.value) return;
  const clientX = e.clientX;
  const deltaX = clientX - lastX;
  if (Math.abs(clientX - startX) > 6) {
    hasMoved = true;
  }
  const now = performance.now();
  const dt = Math.max(1, now - lastTime);
  const angularDelta = deltaX * 0.0035;

  currentAngle.value += angularDelta;
  targetAngle.value = currentAngle.value;
  velocity.value = (angularDelta / dt) * 16.6;

  lastX = clientX;
  lastTime = now;
}

function onPointerUp() {
  if (!isDragging.value) return;
  isDragging.value = false;

  window.removeEventListener('pointermove', onPointerMove);
  window.removeEventListener('pointerup', onPointerUp);
  window.removeEventListener('pointercancel', onPointerUp);

  if (Math.abs(velocity.value) > 0.005) {
    snapToNearest(currentAngle.value + velocity.value * 15);
  } else {
    snapToNearest(currentAngle.value);
  }
}

function snapToNearest(baseAngle: number) {
  const step = stepAngle.value;
  const snappedStep = Math.round(baseAngle / step);
  targetAngle.value = snappedStep * step;
}

function stepPrev() {
  // Step to previous card (centers previous card with exact mathematical alignment)
  const step = stepAngle.value;
  const currentStep = Math.round(targetAngle.value / step);
  targetAngle.value = (currentStep + 1) * step;
}

function stepNext() {
  // Step to next card (centers next card with exact mathematical alignment)
  const step = stepAngle.value;
  const currentStep = Math.round(targetAngle.value / step);
  targetAngle.value = (currentStep - 1) * step;
}

function rotateToIndex(targetIndex: number) {
  const step = stepAngle.value;
  const count = N.value;
  const currentTargetStep = Math.round(targetAngle.value / step);
  const currentNormalized = ((-currentTargetStep % count) + count) % count;

  let diff = targetIndex - currentNormalized;
  if (diff > count / 2) diff -= count;
  if (diff < -count / 2) diff += count;

  targetAngle.value = (currentTargetStep - diff) * step;
}

function onCardClick(index: number) {
  if (hasMoved) return;
  if (index === activeIndex.value) {
    emit('cardClick', props.items[index], index);
  } else {
    rotateToIndex(index);
  }
}

function onSectionPointerMove(e: PointerEvent) {
  if (!sectionRef.value) return;
  const rect = sectionRef.value.getBoundingClientRect();
  const centerX = rect.left + rect.width / 2;
  const centerY = rect.top + rect.height / 2;
  targetMouseX.value = Math.max(-1, Math.min(1, (e.clientX - centerX) / (rect.width / 2)));
  targetMouseY.value = Math.max(-1, Math.min(1, (e.clientY - centerY) / (rect.height / 2)));
}

function onSectionPointerLeave() {
  targetMouseX.value = 0;
  targetMouseY.value = 0;
}

function initThreeGlobe() {
  if (typeof window === 'undefined') return;
  const THREE = (window as any).THREE;
  if (!THREE || !earthCanvasRef.value) return;

  const container = earthCanvasRef.value.parentElement;
  const size = Math.max(300, container ? container.clientWidth : 720);

  threeScene = new THREE.Scene();
  threeCamera = new THREE.PerspectiveCamera(39.5, 1, 0.1, 100);
  threeCamera.position.z = 2.85;

  threeRenderer = new THREE.WebGLRenderer({
    canvas: earthCanvasRef.value,
    alpha: true,
    antialias: true,
    powerPreference: 'high-performance'
  });
  threeRenderer.setSize(size, size);
  threeRenderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 2));

  const ambientLight = new THREE.AmbientLight(0xffffff, 1.12);
  threeScene.add(ambientLight);

  const dirLight = new THREE.DirectionalLight(0xffffff, 0.42);
  dirLight.position.set(-2.5, 3.2, 4);
  threeScene.add(dirLight);

  threeGlobe = new THREE.Group();
  threeScene.add(threeGlobe);

  const textureLoader = new THREE.TextureLoader();
  textureLoader.load(
    props.globeTextureSrc,
    (tex: any) => {
      tex.generateMipmaps = true;
      tex.minFilter = THREE.LinearMipmapLinearFilter;
      tex.magFilter = THREE.LinearFilter;
      if (threeRenderer) {
        tex.anisotropy = Math.min(16, threeRenderer.capabilities.getMaxAnisotropy());
      }
      const geometry = new THREE.SphereGeometry(1, 96, 96);

      // 1. Far side / back continents (faintly visible through transparent front ocean, like glass globe)
      const backMaterial = new THREE.MeshStandardMaterial({
        map: tex,
        transparent: true,
        opacity: 0.35,
        side: THREE.BackSide,
        depthWrite: false,
        roughness: 0.8,
        metalness: 0.02
      });
      const backMesh = new THREE.Mesh(geometry, backMaterial);
      backMesh.renderOrder = 1;
      threeGlobe.add(backMesh);

      // 2. Near side / front continents (crisp white with 100% transparent water)
      const frontMaterial = new THREE.MeshStandardMaterial({
        map: tex,
        transparent: true,
        opacity: 0.98,
        side: THREE.FrontSide,
        depthWrite: true,
        roughness: 0.65,
        metalness: 0.02
      });
      const frontMesh = new THREE.Mesh(geometry, frontMaterial);
      frontMesh.renderOrder = 2;
      threeGlobe.add(frontMesh);

      threeGlobe.rotation.y = 1.8;
      threeRenderer.render(threeScene, threeCamera);
    },
    undefined,
    (err: any) => {
      console.warn('Failed to load globe texture', err);
    }
  );
}

function onResize() {
  updatePositions();
  if (threeRenderer && threeCamera && earthCanvasRef.value?.parentElement) {
    const size = Math.max(300, earthCanvasRef.value.parentElement.clientWidth);
    threeRenderer.setSize(size, size);
    threeCamera.aspect = 1;
    threeCamera.updateProjectionMatrix();
    if (threeScene && threeGlobe) {
      threeRenderer.render(threeScene, threeCamera);
    }
  }
}

onMounted(() => {
  initThreeGlobe();
  window.addEventListener('resize', onResize);
  updatePositions();
  animFrameId = requestAnimationFrame(tick);
});

onBeforeUnmount(() => {
  window.removeEventListener('resize', onResize);
  if (animFrameId) cancelAnimationFrame(animFrameId);
  if (threeRenderer) {
    try { threeRenderer.dispose(); } catch (e) {}
  }
});
</script>

<style scoped>
:root {
  --primary-teal: #588289;
  --light-teal: #90bbc2;
  --sky-mist: #dae9eb;
  --bg-ice: #e1edef;
  --navy-text: #2c3e50;
  --card-w: clamp(200px, 14vw, 240px);
  --card-h: clamp(340px, 24vw, 410px);
  --earth-size: clamp(520px, 72vw, 840px);
  --earth-offset-y: 0px;
}

.hero-orbit-section {
  position: relative;
  width: 100%;
  min-height: 100svh;
  height: 100svh;
  overflow: hidden;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  background: linear-gradient(180deg, #78a3aa 0%, #9fc1c7 40%, #cee0e3 75%, #e1edef 100%);
  user-select: none;
  -webkit-user-select: none;
}

.hero-atmosphere {
  position: absolute;
  inset: 0;
  pointer-events: none;
  z-index: 1;
  background: radial-gradient(circle at 50% 46%, rgba(255, 255, 255, 0.38) 0%, transparent 68%);
}

.orbit-component-container {
  position: relative;
  width: 100%;
  max-width: 90vw;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  margin: 0 auto;
  z-index: 10;
}

.orbit-viewport {
  position: relative;
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: grab;
  touch-action: pan-y pinch-zoom;
}

.orbit-viewport.is-dragging {
  cursor: grabbing;
}

.orbit-stage {
  position: absolute;
  top: 50%;
  left: 50%;
  width: 0;
  height: 0;
  pointer-events: none;
  transform: translateY(-1.2rem);
}

.orbit-ring-guide {
  position: absolute;
  top: 0;
  left: 0;
  border-radius: 50%;
  border: 1.5px dashed rgba(255, 255, 255, 0.32);
  pointer-events: none;
  z-index: 48;
  transform-origin: center center;
}

.earth-container {
  position: absolute;
  top: 0;
  left: 0;
  width: var(--earth-size, 720px);
  height: var(--earth-size, 720px);
  margin-left: calc(var(--earth-size, 720px) / -2);
  margin-top: calc(var(--earth-size, 720px) / -2 + var(--earth-offset-y, 0px));
  border-radius: 50%;
  z-index: 50; /* Base Earth z-index */
  pointer-events: none;
  display: flex;
  align-items: center;
  justify-content: center;
  overflow: hidden;
  box-shadow:
    0 20px 55px rgba(28, 62, 70, 0.38),
    inset 0 0 50px rgba(255, 255, 255, 0.4),
    0 0 75px rgba(144, 187, 194, 0.45);
  transition: margin-top 0.3s ease;
}

.earth-canvas {
  width: 100%;
  height: 100%;
  border-radius: 50%;
  display: block;
  pointer-events: none;
  transform: translate3d(0, 0, 0);
  backface-visibility: hidden;
}

.earth-atmosphere-glow {
  position: absolute;
  inset: 0;
  border-radius: 50%;
  background: radial-gradient(circle at 35% 28%, rgba(255, 255, 255, 0.28) 0%, rgba(255, 255, 255, 0.03) 45%, rgba(144, 187, 194, 0.20) 100%);
  pointer-events: none;
}

.orbit-card {
  position: absolute;
  top: 0;
  left: 0;
  width: var(--card-w, 220px);
  height: var(--card-h, 380px);
  margin-left: calc(var(--card-w, 220px) / -2);
  margin-top: calc(var(--card-h, 380px) / -2);
  border-radius: 16px;
  overflow: hidden;
  cursor: pointer;
  pointer-events: auto;
  transform-origin: center center;
  transition: box-shadow 0.25s ease;
  will-change: transform, filter, z-index;
  background: #111;
  opacity: 1;
}

.orbit-card:hover {
  box-shadow: 0 26px 55px rgba(0, 0, 0, 0.4);
}

.orbit-card.is-active {
  box-shadow:
    0 28px 60px rgba(0, 0, 0, 0.45),
    0 0 0 3px rgba(255, 255, 255, 0.95),
    0 0 35px rgba(255, 255, 255, 0.55);
}

.card-inner {
  position: relative;
  width: 100%;
  height: 100%;
  overflow: hidden;
  border-radius: 16px;
  display: flex;
  flex-direction: column;
  justify-content: flex-end;
}

.card-image {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  object-fit: cover;
  pointer-events: none;
  transition: transform 0.4s ease;
}

.orbit-card:hover .card-image {
  transform: scale(1.04);
}

.card-scrim {
  position: absolute;
  inset: 0;
  background: linear-gradient(
    180deg,
    rgba(0, 0, 0, 0.02) 0%,
    rgba(0, 0, 0, 0.12) 40%,
    rgba(0, 0, 0, 0.78) 80%,
    rgba(0, 0, 0, 0.94) 100%
  );
  pointer-events: none;
}

.card-badge {
  position: absolute;
  top: 0.9rem;
  left: 0.9rem;
  padding: 0.25rem 0.65rem;
  border-radius: 999px;
  font-size: 0.72rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  background: rgba(0, 0, 0, 0.45);
  backdrop-filter: blur(8px);
  color: #fff;
  border: 1px solid rgba(255, 255, 255, 0.25);
}

.card-title {
  position: relative;
  z-index: 2;
  padding: 1.15rem 1rem;
  font-size: 1.18rem;
  font-weight: 700;
  color: #ffffff;
  line-height: 1.25;
  text-shadow: 0 2px 6px rgba(0, 0, 0, 0.6);
  font-family: 'Figtree', sans-serif;
  text-wrap: balance;
}

.nav-arrow {
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
  width: 48px;
  height: 48px;
  border-radius: 50%;
  background: rgba(255, 255, 255, 0.75);
  backdrop-filter: blur(10px);
  border: 1px solid rgba(255, 255, 255, 0.9);
  color: #2c3e50;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  z-index: 250;
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.12);
  transition: all 0.2s cubic-bezier(0.2, 0.8, 0.2, 1);
}

.nav-arrow:hover {
  background: #ffffff;
  transform: translateY(-50%) scale(1.1);
  box-shadow: 0 10px 28px rgba(0, 0, 0, 0.18);
}

.nav-arrow.prev { left: 0.5rem; }
.nav-arrow.next { right: 0.5rem; }

/* Half-circle pedestal at bottom edge */
.bottom-half-circle-pedestal {
  position: absolute;
  bottom: 0;
  left: 50%;
  transform: translateX(-50%);
  width: clamp(340px, 40vw, 560px);
  height: 5.2rem;
  background: #ffffff;
  border-radius: 50% 50% 0 0 / 100% 100% 0 0;
  box-shadow:
    0 -10px 35px rgba(28, 62, 70, 0.16),
    0 -2px 10px rgba(88, 130, 137, 0.1);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  z-index: 150;
  padding-top: 0.6rem;
  padding-bottom: 0.2rem;
}

.orbit-dots {
  display: flex;
  align-items: center;
  gap: 0.55rem;
}

.orbit-dot {
  width: 9px;
  height: 9px;
  border-radius: 50%;
  background: rgba(88, 130, 137, 0.35);
  border: none;
  cursor: pointer;
  transition: all 0.25s cubic-bezier(0.34, 1.56, 0.64, 1);
}

.orbit-dot.is-active {
  width: 24px;
  border-radius: 999px;
  background: #588289;
  box-shadow: 0 2px 8px rgba(88, 130, 137, 0.45);
}

.all-updates-btn {
  display: inline-flex;
  align-items: center;
  gap: 0.4rem;
  font-size: 0.95rem;
  font-weight: 700;
  color: #588289;
  text-decoration: none;
  padding: 0.3rem 0.9rem;
  border-radius: 999px;
  background: rgba(88, 130, 137, 0.1);
  transition: all 0.2s ease;
}

.all-updates-btn:hover {
  background: #588289;
  color: #ffffff;
  transform: translateY(-1px);
  box-shadow: 0 4px 12px rgba(88, 130, 137, 0.25);
}

@media (max-width: 1024px) {
  :root {
    --card-w: clamp(185px, 22vw, 220px);
    --card-h: clamp(320px, 38vh, 380px);
    --earth-size: clamp(380px, 66vw, 530px);
    --earth-offset-y: -75px;
  }
  .orbit-component-container { max-width: 95vw; }
  .bottom-half-circle-pedestal { width: clamp(320px, 58vw, 440px); height: 4.8rem; }
  .orbit-stage { transform: translateY(0.5rem); }
}

@media (max-width: 640px) {
  :root {
    --card-w: clamp(165px, 46vw, 205px);
    --card-h: clamp(285px, 42vh, 345px);
    --earth-size: clamp(310px, 80vw, 390px);
    --earth-offset-y: -90px;
  }
  .bottom-half-circle-pedestal { width: 88vw; height: 4.5rem; }
  .card-title { font-size: 0.98rem; padding: 0.8rem; }
  .orbit-stage { transform: translateY(1.2rem); }
}
</style>

// TapeKidsOrbitSlider.tsx
import React, { useState, useEffect, useRef } from 'react';

export interface OrbitCardItem {
  id: string | number;
  title: string;
  category?: string;
  image: string;
  url?: string;
}

export interface TapeKidsOrbitSliderProps {
  items?: OrbitCardItem[];
  globeMode?: 'webgl' | 'video';
  globeTextureSrc?: string;
  globeVideoSrc?: string;
  globePosterSrc?: string;
  allUpdatesLink?: string;
  autoRotateSpeed?: number;
  onCardClick?: (card: OrbitCardItem, index: number) => void;
  onActiveChange?: (index: number) => void;
}

const DEFAULT_CARDS: OrbitCardItem[] = [
  {
    id: "its-in-you",
    title: "It's In You",
    category: "Creations",
    image: "https://content.branham.org/assets/1/1207762fc30598f35e7262400dfc2b8528b032c5d89cccd6fd33581fa77e6623d8a701e8a2c0f9b9d6fde6e9b00c6d72d5ae2b9a8147676a928b055b5529ee36.jpg"
  },
  {
    id: "god-rich-mercy",
    title: "The God Who Is Rich In Mercy",
    category: "Updates",
    image: "https://content.branham.org/assets/1/ab15cb9a63ce0bf60b33e90bc7d110578b1dcadcf36db9ba72019aa644056842c9ae8c67f3861c462b1f51158636ced1362d45c9a0d24f44274fd5d899a4fe66.jpg"
  },
  {
    id: "coloring-book-stats",
    title: "Coloring Book Stats",
    category: "Creations",
    image: "https://content.branham.org/assets/1/a8cd614bf399629ea9aecf455a8a243064d1529900aba8957946759940433587d12a30ee73ae5894f207cd561b924cc7cf997facd0eda45aa7e61915692485db.jpg"
  },
  {
    id: "wesley-birthplace",
    title: "John Wesley's Birthplace",
    category: "History",
    image: "https://content.branham.org/assets/1/77a4cd54ab94035f9912126356f7466c0d8c8df36ca18e28cdb0f26fddb75a9aa2b37b226aa009b4339d202ef6d2ab437da82dca9558441d130ef7067c02ac89.png"
  },
  {
    id: "save-tapekids-app",
    title: "Save TapeKids.org to your smartphone home screen",
    category: "Tips",
    image: "https://content.branham.org/assets/1/e0a22d013c3842d1d6ef52771f53bba97f6c290ce55036199e76993615d007109d22d56d801e1b44ebe5605be1e0c2e9aed9c01638c0671e670e5f42bdf0f3b7.jpg"
  },
  {
    id: "laodicean-age",
    title: "The Laodicean Church Age",
    category: "Church Ages",
    image: "https://content.branham.org/assets/1/9eaee6098b2c9e9eaceeb142b61a576389ba617f330e9ebeabc2cf68ffc69ba9b558edd23a895c5983c7c6a0f8a4f883fb46ec5f6e34177186dded38e92b0145.jpg"
  }
];

export const TapeKidsOrbitSlider: React.FC<TapeKidsOrbitSliderProps> = ({
  items = DEFAULT_CARDS,
  globeMode = 'webgl',
  globeTextureSrc = '/earth-texture.png',
  allUpdatesLink = "https://tapekids.org/en/updates",
  autoRotateSpeed = 0.0016,
  onCardClick,
  onActiveChange
}) => {
  const [currentAngle, setCurrentAngle] = useState(0);
  const [targetAngle, setTargetAngle] = useState(0);
  const [activeIndex, setActiveIndex] = useState(0);
  const [isDragging, setIsDragging] = useState(false);

  const sectionRef = useRef<HTMLElement | null>(null);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const threeRef = useRef<{ scene: any; camera: any; renderer: any; globe: any } | null>(null);
  const currentAngleRef = useRef(0);
  const targetAngleRef = useRef(0);
  const lastAngleRef = useRef(0);
  const velocityRef = useRef(0);
  const isDraggingRef = useRef(false);
  const animFrameRef = useRef<number | null>(null);

  // Subtle Mouseover Parallax Refs
  const targetMouseXRef = useRef(0);
  const targetMouseYRef = useRef(0);
  const smoothMouseXRef = useRef(0);
  const smoothMouseYRef = useRef(0);

  const startXRef = useRef(0);
  const lastXRef = useRef(0);
  const lastTimeRef = useRef(0);
  const hasMovedRef = useRef(false);

  const lastTickTimeRef = useRef(performance.now());

  const N = items.length;
  const stepAngle = (2 * Math.PI) / N;

  const getOrbitParams = () => {
    const w = typeof window !== 'undefined' ? window.innerWidth : 1200;
    let earthSize: number, cardW: number, tiltDeg: number, cardScaleMin: number, earthOffsetY: number, stageShiftY: string;

    if (w <= 640) {
      earthSize = Math.min(w * 0.80, 390);
      cardW = Math.min(w * 0.48, 205);
      tiltDeg = 7;
      cardScaleMin = 0.65;
      earthOffsetY = -90;
      stageShiftY = '1.2rem';
      const rx = w * 0.52;
      const rz = Math.round(rx * 0.50);
      return { rx, rz, tiltDeg, cardScaleMin, earthSize, earthOffsetY, stageShiftY, cardW };
    } else if (w <= 1024) {
      earthSize = Math.min(w * 0.66, 540);
      cardW = Math.min(w * 0.22, 220);
      tiltDeg = 8;
      cardScaleMin = 0.68;
      earthOffsetY = -75;
      stageShiftY = '0.5rem';
      const rGlobe = earthSize / 2;
      const minClearanceRx = (rGlobe + (cardW / 2) + 10) / 0.866;
      const maxRx = (w / 2) - (cardW / 2) - 18;
      const rx = Math.min(maxRx, Math.max(minClearanceRx, w * 0.40));
      const rz = Math.round(rx * 0.52);
      return { rx, rz, tiltDeg, cardScaleMin, earthSize, earthOffsetY, stageShiftY, cardW };
    } else {
      // 72vw max on large screens
      earthSize = Math.min(w * 0.72, 840);
      cardW = Math.min(w * 0.14, 230);
      tiltDeg = 9;
      cardScaleMin = 0.70;
      earthOffsetY = 0;
      stageShiftY = '-1.2rem';
      const rGlobe = earthSize / 2;
      const minClearanceRx = (rGlobe + (cardW / 2) + 16) / 0.866;
      const maxRx = (w / 2) - (cardW / 2) - 32;
      const rx = Math.min(maxRx, Math.max(minClearanceRx, w * 0.40));
      const rz = Math.round(rx * 0.54);
      return { rx, rz, tiltDeg, cardScaleMin, earthSize, earthOffsetY, stageShiftY, cardW };
    }
  };

  const stepPrev = () => {
    const currentStep = Math.round(targetAngleRef.current / stepAngle);
    const next = (currentStep + 1) * stepAngle;
    targetAngleRef.current = next;
    setTargetAngle(next);
  };

  const stepNext = () => {
    const currentStep = Math.round(targetAngleRef.current / stepAngle);
    const next = (currentStep - 1) * stepAngle;
    targetAngleRef.current = next;
    setTargetAngle(next);
  };

  const rotateToIndex = (targetIndex: number) => {
    const currentStep = Math.round(targetAngleRef.current / stepAngle);
    const normalized = ((-currentStep % N) + N) % N;
    let diff = targetIndex - normalized;
    if (diff > N / 2) diff -= N;
    if (diff < -N / 2) diff += N;
    const next = (currentStep - diff) * stepAngle;
    targetAngleRef.current = next;
    setTargetAngle(next);
  };

  const onSectionPointerMove = (e: React.PointerEvent) => {
    if (!sectionRef.current) return;
    const rect = sectionRef.current.getBoundingClientRect();
    const centerX = rect.left + rect.width / 2;
    const centerY = rect.top + rect.height / 2;
    targetMouseXRef.current = Math.max(-1, Math.min(1, (e.clientX - centerX) / (rect.width / 2)));
    targetMouseYRef.current = Math.max(-1, Math.min(1, (e.clientY - centerY) / (rect.height / 2)));
  };

  const onSectionPointerLeave = () => {
    targetMouseXRef.current = 0;
    targetMouseYRef.current = 0;
  };

  const onPointerDown = (e: React.PointerEvent) => {
    if (e.button !== 0) return;
    isDraggingRef.current = true;
    setIsDragging(true);
    hasMovedRef.current = false;
    startXRef.current = e.clientX;
    lastXRef.current = e.clientX;
    lastTimeRef.current = performance.now();
    velocityRef.current = 0;

    window.addEventListener('pointermove', onPointerMove);
    window.addEventListener('pointerup', onPointerUp);
    window.addEventListener('pointercancel', onPointerUp);
  };

  const onPointerMove = (e: PointerEvent) => {
    if (!isDraggingRef.current) return;
    const clientX = e.clientX;
    const deltaX = clientX - lastXRef.current;
    if (Math.abs(clientX - startXRef.current) > 6) {
      hasMovedRef.current = true;
    }
    const now = performance.now();
    const dt = Math.max(1, now - lastTimeRef.current);
    const angularDelta = deltaX * 0.0035;

    currentAngleRef.current += angularDelta;
    targetAngleRef.current = currentAngleRef.current;
    velocityRef.current = (angularDelta / dt) * 16.6;

    lastXRef.current = clientX;
    lastTimeRef.current = now;
    setCurrentAngle(currentAngleRef.current);
  };

  const onPointerUp = () => {
    if (!isDraggingRef.current) return;
    isDraggingRef.current = false;
    setIsDragging(false);

    window.removeEventListener('pointermove', onPointerMove);
    window.removeEventListener('pointerup', onPointerUp);
    window.removeEventListener('pointercancel', onPointerUp);

    const base = Math.abs(velocityRef.current) > 0.005
      ? currentAngleRef.current + velocityRef.current * 15
      : currentAngleRef.current;

    const snapped = Math.round(base / stepAngle) * stepAngle;
    targetAngleRef.current = snapped;
    setTargetAngle(snapped);
  };

  useEffect(() => {
    if (typeof window !== 'undefined' && canvasRef.current) {
      const THREE = (window as any).THREE;
      if (THREE) {
        const canvas = canvasRef.current;
        const container = canvas.parentElement;
        const size = Math.max(300, container ? container.clientWidth : 720);
        const scene = new THREE.Scene();
        const camera = new THREE.PerspectiveCamera(39.5, 1, 0.1, 100);
        camera.position.z = 2.85;

        const renderer = new THREE.WebGLRenderer({
          canvas,
          alpha: true,
          antialias: true,
          powerPreference: 'high-performance'
        });
        renderer.setSize(size, size);
        renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 2));

        const ambientLight = new THREE.AmbientLight(0xffffff, 1.12);
        scene.add(ambientLight);

        const dirLight = new THREE.DirectionalLight(0xffffff, 0.42);
        dirLight.position.set(-2.5, 3.2, 4);
        scene.add(dirLight);

        const globe = new THREE.Group();
        scene.add(globe);

        const textureLoader = new THREE.TextureLoader();
        textureLoader.load(globeTextureSrc, (tex: any) => {
          tex.generateMipmaps = true;
          tex.minFilter = THREE.LinearMipmapLinearFilter;
          tex.magFilter = THREE.LinearFilter;
          if (renderer) {
            tex.anisotropy = Math.min(16, renderer.capabilities.getMaxAnisotropy());
          }
          const geometry = new THREE.SphereGeometry(1, 96, 96);

          // 1. Far side / back continents (faintly visible through transparent front ocean)
          const backMaterial = new THREE.MeshStandardMaterial({
            map: tex,
            transparent: true,
            opacity: 0.35,
            side: THREE.BackSide,
            depthWrite: false,
            roughness: 0.8,
            metalness: 0.02
          });
          const backMesh = new THREE.Mesh(geometry, backMaterial);
          backMesh.renderOrder = 1;
          globe.add(backMesh);

          // 2. Near side / front continents (crisp white with 100% transparent water)
          const frontMaterial = new THREE.MeshStandardMaterial({
            map: tex,
            transparent: true,
            opacity: 0.98,
            side: THREE.FrontSide,
            depthWrite: true,
            roughness: 0.65,
            metalness: 0.02
          });
          const frontMesh = new THREE.Mesh(geometry, frontMaterial);
          frontMesh.renderOrder = 2;
          globe.add(frontMesh);

          globe.rotation.y = 1.8;
          threeRef.current = { scene, camera, renderer, globe };
          renderer.render(scene, camera);
        });
      }
    }

    const tick = () => {
      smoothMouseXRef.current += (targetMouseXRef.current - smoothMouseXRef.current) * 0.08;
      smoothMouseYRef.current += (targetMouseYRef.current - smoothMouseYRef.current) * 0.08;

      if (!isDraggingRef.current) {
        if (Math.abs(velocityRef.current) > 0.0002) {
          currentAngleRef.current += velocityRef.current;
          velocityRef.current *= 0.92;
          setCurrentAngle(currentAngleRef.current);
        } else {
          velocityRef.current = 0;
          const diff = targetAngleRef.current - currentAngleRef.current;
          if (Math.abs(diff) > 0.0002) {
            currentAngleRef.current += diff * 0.12;
            setCurrentAngle(currentAngleRef.current);
          } else {
            currentAngleRef.current = targetAngleRef.current;
            setCurrentAngle(currentAngleRef.current);
          }
        }
      }

      const sliderDelta = currentAngleRef.current - lastAngleRef.current;
      lastAngleRef.current = currentAngleRef.current;

      if (globeMode === 'webgl' && threeRef.current?.renderer && threeRef.current?.globe) {
        threeRef.current.globe.rotation.y += 0.0028 + sliderDelta * 0.85;
        threeRef.current.renderer.render(threeRef.current.scene, threeRef.current.camera);
      }

      let closestDist = Infinity;
      let newActive = 0;
      for (let i = 0; i < N; i++) {
        const theta = currentAngleRef.current + i * stepAngle;
        const normAngle = ((theta % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);
        const dist = Math.min(normAngle, 2 * Math.PI - normAngle);
        if (dist < closestDist) {
          closestDist = dist;
          newActive = i;
        }
      }
      setActiveIndex(newActive);
      onActiveChange?.(newActive);

      animFrameRef.current = requestAnimationFrame(tick);
    };

    animFrameRef.current = requestAnimationFrame(tick);
    return () => {
      if (animFrameRef.current) cancelAnimationFrame(animFrameRef.current);
      if (threeRef.current?.renderer) {
        try { threeRef.current.renderer.dispose(); } catch (e) {}
      }
    };
  }, [N, stepAngle, onActiveChange, globeMode, globeTextureSrc]);

  const { rx, rz, tiltDeg, cardScaleMin, earthSize, earthOffsetY, stageShiftY, cardW } = getOrbitParams();
  const tiltRad = (tiltDeg * Math.PI) / 180;

  return (
    <section
      ref={sectionRef}
      onPointerMove={onSectionPointerMove}
      onPointerLeave={onSectionPointerLeave}
      style={{
      position: 'relative',
      width: '100%',
      minHeight: '100svh',
      height: '100svh',
      overflow: 'hidden',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      background: 'linear-gradient(180deg, #78a3aa 0%, #9fc1c7 40%, #cee0e3 75%, #e1edef 100%)',
      userSelect: 'none'
    }}>
      {/* Atmosphere subtle radiance */}
      <div style={{
        position: 'absolute',
        inset: 0,
        pointerEvents: 'none',
        zIndex: 1,
        background: 'radial-gradient(circle at 50% 46%, rgba(255, 255, 255, 0.38) 0%, transparent 68%)'
      }} />

      {/* Earth and Slides Container: max-width 90vw, centered in viewport */}
      <div style={{
        position: 'relative',
        width: '100%',
        maxWidth: '90vw',
        height: '100%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        margin: '0 auto',
        zIndex: 10
      }}>
        {/* Orbit Viewport */}
        <div
          style={{
            position: 'relative',
            width: '100%',
            height: '100%',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            cursor: isDragging ? 'grabbing' : 'grab',
            touchAction: 'pan-y pinch-zoom'
          }}
          onPointerDown={onPointerDown}
          onMouseEnter={() => { isHoveredRef.current = true; }}
          onMouseLeave={() => { isHoveredRef.current = false; }}
        >
          {/* Orbit Stage */}
          <div style={{
            position: 'absolute',
            top: '50%',
            left: '50%',
            width: 0,
            height: 0,
            pointerEvents: 'none',
            transform: `translateY(${stageShiftY})`
          }}>
            {/* Guide Ring */}
            <div style={{
              position: 'absolute',
              top: 0,
              left: 0,
              width: rx * 2 + 80,
              height: rz * 2 + 50,
              marginLeft: -(rx + 40),
              marginTop: -(rz + 25),
              borderRadius: '50%',
              border: '1.5px dashed rgba(255, 255, 255, 0.32)',
              pointerEvents: 'none',
              zIndex: 48,
              transform: 'rotateX(74deg)'
            }} />

            {/* Earth in the Middle */}
            <div style={{
              position: 'absolute',
              top: 0,
              left: 0,
              width: earthSize,
              height: earthSize,
              marginLeft: -earthSize / 2,
              marginTop: -earthSize / 2 + earthOffsetY,
              borderRadius: '50%',
              zIndex: 50,
              pointerEvents: 'none',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              overflow: 'hidden',
              boxShadow: '0 20px 55px rgba(28, 62, 70, 0.38), inset 0 0 50px rgba(255, 255, 255, 0.4), 0 0 75px rgba(144, 187, 194, 0.45)',
              transition: 'margin-top 0.3s ease'
            }}>
              <canvas
                ref={canvasRef}
                style={{
                  width: '100%',
                  height: '100%',
                  borderRadius: '50%',
                  display: 'block',
                  pointerEvents: 'none',
                  transform: 'translate3d(0, 0, 0)',
                  backfaceVisibility: 'hidden'
                }}
              />
              <div style={{
                position: 'absolute',
                inset: 0,
                borderRadius: '50%',
                background: 'radial-gradient(circle at 35% 28%, rgba(255, 255, 255, 0.28) 0%, rgba(255, 255, 255, 0.03) 45%, rgba(144, 187, 194, 0.20) 100%)',
                pointerEvents: 'none'
              }} />
            </div>

            {/* Cards as direct siblings */}
            {items.map((card, i) => {
              const theta = currentAngle + i * stepAngle;
              const cosT = Math.cos(theta);
              const sinT = Math.sin(theta);
              const x = sinT * rx;
              const z = cosT * rz;
              const y = -cosT * Math.sin(tiltRad) * 65;
              const normZ = (z + rz) / (2 * rz);

              // Active Card Hero Scaling: blossoms to ~1.36x scale at front center
              const baseScale = cardScaleMin + normZ * (1.0 - cardScaleMin);
              const focalBoost = Math.pow(normZ, 2.8) * 0.36;
              const scale = baseScale + focalBoost;

              const rotateY = -sinT * 22;
              const rotateZ = -sinT * 2.5;

              // Subtle mouseover animation pull (active card pulls most noticeably, disabled during drag):
              const pullFactor = 0.35 + 0.65 * Math.pow(normZ, 2.0);
              const pullX = isDragging ? 0 : smoothMouseXRef.current * 16 * pullFactor;
              const pullY = isDragging ? 0 : smoothMouseYRef.current * 5 * pullFactor;
              const pullRotY = isDragging ? 0 : smoothMouseXRef.current * 2.5 * pullFactor;
              const pullRotX = isDragging ? 0 : -smoothMouseYRef.current * 1.5 * pullFactor;

              // Inactive cards: fully opaque with realistic contrast & depth attenuation
              const contrast = 0.72 + normZ * 0.28;
              const brightness = 0.88 + normZ * 0.12;

              let zIndex: number;
              let opacity: number;
              let pointerEvents: 'auto' | 'none';
              let visibility: 'visible' | 'hidden';
              let filter = 'none';

              if (normZ >= 0.55) {
                // Front hemisphere: 100% FULLY OPAQUE, crisp, interactive
                zIndex = 70 + Math.round(normZ * 30);
                opacity = 1;
                pointerEvents = 'auto';
                visibility = 'visible';
                if (normZ <= 0.88) {
                  filter = `contrast(${contrast.toFixed(2)}) brightness(${brightness.toFixed(2)})`;
                }
              } else if (normZ >= 0.45) {
                // Horizon edge transition: smoothly fades in/out as cards round behind the globe
                const fade = (normZ - 0.45) / 0.1;
                zIndex = 55 + Math.round(normZ * 10);
                opacity = fade;
                pointerEvents = 'none';
                visibility = 'visible';
                filter = `contrast(${contrast.toFixed(2)}) brightness(${brightness.toFixed(2)})`;
              } else {
                // Far side of the globe: strictly hidden to eliminate any overlapping or ghosting
                zIndex = 1;
                opacity = 0;
                pointerEvents = 'none';
                visibility = 'hidden';
              }

              const isActive = activeIndex === i;

              return (
                <div
                  key={card.id || i}
                  onClick={() => {
                    if (hasMovedRef.current) return;
                    if (isActive) {
                      onCardClick?.(card, i);
                    } else {
                      rotateToIndex(i);
                    }
                  }}
                  style={{
                    position: 'absolute',
                    top: 0,
                    left: 0,
                    width: cardW,
                    height: Math.round(cardW * 1.7),
                    marginLeft: -cardW / 2,
                    marginTop: -Math.round(cardW * 1.7) / 2,
                    borderRadius: 16,
                    overflow: 'hidden',
                    cursor: 'pointer',
                    pointerEvents,
                    visibility,
                    transformOrigin: 'center center',
                    transform: `perspective(1200px) translate3d(${(x + pullX).toFixed(1)}px, ${(y + pullY).toFixed(1)}px, 0) rotateX(${pullRotX.toFixed(1)}deg) rotateY(${(rotateY + pullRotY).toFixed(1)}deg) rotateZ(${rotateZ.toFixed(1)}deg) scale(${scale.toFixed(3)})`,
                    zIndex,
                    opacity,
                    filter,
                    boxShadow: isActive
                      ? '0 28px 60px rgba(0, 0, 0, 0.45), 0 0 0 3px rgba(255, 255, 255, 0.95), 0 0 35px rgba(255, 255, 255, 0.55)'
                      : 'none',
                    transition: 'box-shadow 0.25s ease',
                    background: '#111'
                  }}
                >
                  <div style={{ position: 'relative', width: '100%', height: '100%', overflow: 'hidden', display: 'flex', flexDirection: 'column', justifyContent: 'flex-end' }}>
                    <img
                      src={card.image}
                      alt={card.title}
                      loading="lazy"
                      style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover' }}
                    />
                    <div style={{
                      position: 'absolute',
                      inset: 0,
                      background: 'linear-gradient(180deg, rgba(0,0,0,0.02) 0%, rgba(0,0,0,0.12) 40%, rgba(0,0,0,0.78) 80%, rgba(0,0,0,0.94) 100%)'
                    }} />
                    {card.category && (
                      <div style={{
                        position: 'absolute',
                        top: '0.9rem',
                        left: '0.9rem',
                        padding: '0.25rem 0.65rem',
                        borderRadius: 999,
                        fontSize: '0.72rem',
                        fontWeight: 700,
                        textTransform: 'uppercase',
                        letterSpacing: '0.05em',
                        background: 'rgba(0, 0, 0, 0.45)',
                        backdropFilter: 'blur(8px)',
                        color: '#fff',
                        border: '1px solid rgba(255, 255, 255, 0.25)'
                      }}>
                        {card.category}
                      </div>
                    )}
                    <h3 style={{
                      position: 'relative',
                      zIndex: 2,
                      padding: '1.15rem 1rem',
                      fontSize: '1.18rem',
                      fontWeight: 700,
                      color: '#fff',
                      lineHeight: 1.25,
                      fontFamily: 'Figtree, sans-serif',
                      textWrap: 'balance'
                    }}>
                      {card.title}
                    </h3>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Chevrons */}
        <button
          onClick={stepPrev}
          aria-label="Previous card"
          style={{
            position: 'absolute',
            top: '50%',
            left: '0.5rem',
            transform: 'translateY(-50%)',
            width: 48,
            height: 48,
            borderRadius: '50%',
            background: 'rgba(255, 255, 255, 0.75)',
            backdropFilter: 'blur(10px)',
            border: '1px solid rgba(255, 255, 255, 0.9)',
            color: '#2c3e50',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            cursor: 'pointer',
            zIndex: 250,
            boxShadow: '0 8px 24px rgba(0, 0, 0, 0.12)'
          }}
        >
          ◀
        </button>
        <button
          onClick={stepNext}
          aria-label="Next card"
          style={{
            position: 'absolute',
            top: '50%',
            right: '0.5rem',
            transform: 'translateY(-50%)',
            width: 48,
            height: 48,
            borderRadius: '50%',
            background: 'rgba(255, 255, 255, 0.75)',
            backdropFilter: 'blur(10px)',
            border: '1px solid rgba(255, 255, 255, 0.9)',
            color: '#2c3e50',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            cursor: 'pointer',
            zIndex: 250,
            boxShadow: '0 8px 24px rgba(0, 0, 0, 0.12)'
          }}
        >
          ▶
        </button>
      </div>

      {/* Bottom Contrasting Half-Circle Pedestal */}
      <div style={{
        position: 'absolute',
        bottom: 0,
        left: '50%',
        transform: 'translateX(-50%)',
        width: 'clamp(340px, 40vw, 560px)',
        height: '5.2rem',
        background: '#ffffff',
        borderRadius: '50% 50% 0 0 / 100% 100% 0 0',
        boxShadow: '0 -10px 35px rgba(28, 62, 70, 0.16), 0 -2px 10px rgba(88, 130, 137, 0.1)',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '0.5rem',
        zIndex: 150,
        paddingTop: '0.6rem',
        paddingBottom: '0.2rem'
      }}>
        {/* Dots */}
        <div style={{ display: 'flex', gap: '0.55rem', alignItems: 'center' }}>
          {items.map((_, i) => (
            <button
              key={i}
              onClick={() => rotateToIndex(i)}
              style={{
                width: activeIndex === i ? 24 : 9,
                height: 9,
                borderRadius: 999,
                background: activeIndex === i ? '#588289' : 'rgba(88, 130, 137, 0.35)',
                border: 'none',
                cursor: 'pointer',
                transition: 'all 0.25s ease'
              }}
            />
          ))}
        </div>
        {/* All Updates button */}
        <a
          href={allUpdatesLink}
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: '0.4rem',
            fontSize: '0.95rem',
            fontWeight: 700,
            color: '#588289',
            textDecoration: 'none',
            padding: '0.3rem 0.9rem',
            borderRadius: 999,
            background: 'rgba(88, 130, 137, 0.1)',
            transition: 'all 0.2s ease'
          }}
        >
          All Updates →
        </a>
      </div>
    </section>
  );
};

export default TapeKidsOrbitSlider;
